import { onValue, ref, type Database } from "firebase/database";

import {
  visitSlideElements,
  type Presentation,
  type ScriptedElement,
  type Slide,
} from "@powershow/document-schema";

import type { PlayerController } from "./player";

export const SCRIPTED_ACTION_ROOT_PATH = "live/scriptedAction";

export interface LiveScriptedActionRecord {
  activationRevision: number;
  currentVersionId: string;
  revision: number;
  pageId: string;
  elementId: string;
  portId: string;
  targetBootId: string;
}

function nonNegativeInteger(value: unknown): value is number {
  return typeof value === "number" &&
    Number.isFinite(value) &&
    Number.isInteger(value) &&
    value >= 0;
}

function nonEmptyLiveString(value: unknown): value is string {
  return typeof value === "string" && value.trim() !== "";
}

function canonicalId(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

function plainRecord(value: unknown): value is Record<string, unknown> {
  return value !== null &&
    typeof value === "object" &&
    !Array.isArray(value) &&
    Object.prototype.toString.call(value) === "[object Object]";
}

/** Strict parser for the boot-scoped Scripted action occurrence record. */
export function parseLiveScriptedActionRecord(
  value: unknown,
): LiveScriptedActionRecord | null {
  if (!plainRecord(value)) return null;

  const keys = [
    "activationRevision",
    "currentVersionId",
    "revision",
    "pageId",
    "elementId",
    "portId",
    "targetBootId",
  ] as const;
  const actualKeys = Object.keys(value);
  if (actualKeys.length !== keys.length || !keys.every((key) =>
    Object.prototype.hasOwnProperty.call(value, key))) {
    return null;
  }

  if (!nonNegativeInteger(value.activationRevision) ||
    !nonEmptyLiveString(value.currentVersionId) ||
    !nonNegativeInteger(value.revision) || value.revision < 1 ||
    !nonEmptyLiveString(value.pageId) ||
    !canonicalId(value.elementId) ||
    !canonicalId(value.portId) ||
    !nonEmptyLiveString(value.targetBootId)) {
    return null;
  }

  return {
    activationRevision: value.activationRevision,
    currentVersionId: value.currentVersionId.trim(),
    revision: value.revision,
    pageId: value.pageId.trim(),
    elementId: value.elementId,
    portId: value.portId,
    targetBootId: value.targetBootId.trim(),
  };
}

/** Parses only canonical decimal RTDB indexes generated by the writer. */
export function parseScriptedActionIndex(key: string): number | null {
  if (!/^(0|[1-9]\d*)$/.test(key)) return null;
  const index = Number(key);
  return nonNegativeInteger(index) ? index : null;
}

interface ScriptedActionTracker {
  prepareBoot(targetBootId: string): void;
  takeDelta(
    scriptedSlot: number,
    portIndex: number,
    record: LiveScriptedActionRecord,
  ): number;
}

/** Keeps occurrence cursors for one Player browser runtime, not one subscription. */
export function createLiveScriptedActionTracker(): ScriptedActionTracker {
  let bootId: string | undefined;
  const highWater = new Map<string, number>();

  return {
    prepareBoot(targetBootId): void {
      if (bootId === targetBootId) return;
      bootId = targetBootId;
      highWater.clear();
    },
    takeDelta(scriptedSlot, portIndex, record): number {
      const identity = JSON.stringify([
        scriptedSlot,
        portIndex,
        record.activationRevision,
        record.currentVersionId,
        record.pageId,
        record.elementId,
        record.portId,
        record.targetBootId,
      ]);
      const lastSeen = highWater.get(identity) ?? 0;
      if (record.revision <= lastSeen) return 0;
      highWater.set(identity, record.revision);
      return record.revision - lastSeen;
    },
  };
}

function scriptedsOnSlide(slide: Slide): ScriptedElement[] {
  const scripteds: ScriptedElement[] = [];
  visitSlideElements(slide, (element) => {
    if (element.type === "scripted") scripteds.push(element);
  });
  return scripteds;
}

function numericEntries(value: unknown): Array<[string, unknown]> {
  return value !== null && typeof value === "object"
    ? Object.entries(value)
    : [];
}

/**
 * Subscribes once to the generated action tree and translates unseen counter
 * revisions into best-effort Player action occurrences.
 */
export function subscribeLiveScriptedAction(
  database: Database,
  activationRevision: number,
  currentVersionId: string,
  targetBootId: string,
  presentation: Presentation,
  controller: PlayerController,
  tracker: ScriptedActionTracker,
): () => void {
  tracker.prepareBoot(targetBootId);

  const unsubscribe = onValue(
    ref(database, SCRIPTED_ACTION_ROOT_PATH),
    (snapshot) => {
      for (const [slotKey, ports] of numericEntries(snapshot.val())) {
        const scriptedSlot = parseScriptedActionIndex(slotKey);
        if (scriptedSlot === null) continue;

        for (const [portKey, value] of numericEntries(ports)) {
          const portIndex = parseScriptedActionIndex(portKey);
          const record = parseLiveScriptedActionRecord(value);
          if (portIndex === null || record === null ||
            record.activationRevision !== activationRevision ||
            record.currentVersionId !== currentVersionId ||
            record.targetBootId !== targetBootId) {
            continue;
          }

          const delta = tracker.takeDelta(scriptedSlot, portIndex, record);
          if (delta === 0) continue;

          const currentSlide = presentation.slides[controller.getCurrentIndex()];
          if (!currentSlide || currentSlide.id !== record.pageId) continue;

          const scripted = scriptedsOnSlide(currentSlide)[scriptedSlot];
          const port = scripted?.ports[portIndex];
          if (!scripted || scripted.id !== record.elementId ||
            !port || port.kind !== "action" || port.id !== record.portId) {
            continue;
          }

          for (let occurrence = 0; occurrence < delta; occurrence += 1) {
            controller.sendScriptedAction(record.elementId, record.portId);
          }
        }
      }
    },
  );

  return () => unsubscribe();
}
