import { describe, expect, it, vi } from "vitest";
import { PresentationSchema } from "@powershow/document-schema";
const firebase = vi.hoisted(() => ({ onValue: vi.fn(), ref: vi.fn(), callback: undefined as ((snapshot: { val(): unknown }) => void) | undefined }));
vi.mock("firebase/database", () => ({ onValue: firebase.onValue, ref: firebase.ref }));
import { createLiveScriptedInputTracker, subscribeLiveScriptedInput } from "../src/live-scripted-input";
const presentation = PresentationSchema.parse({ schemaVersion: 1, id: "p", title: "P", description: "", aspectRatio: "16:9", slides: [{ id: "page", elements: [{ id: "s", type: "scripted", title: "S", html: "", css: "", script: "", ports: [{ id: "n", label: "N", kind: "number", direction: "input", min: 0, max: 1, step: .5 }, { id: "b", label: "B", kind: "boolean", direction: "input-output" }, { id: "out", label: "Out", kind: "boolean", direction: "output" }, { id: "act", label: "Act", kind: "action" }] }] }] });
const input = (overrides: Record<string, unknown> = {}) => ({ activationRevision: 7, currentVersionId: "v", revision: 1, pageId: "page", elementId: "s", portId: "n", targetBootId: "boot", targetMountRevision: 2, value: .12, ...overrides });
function setup(mountRevision = 2) {
  let currentMountRevision = mountRevision;
  const sendScriptedInput = vi.fn(); firebase.ref.mockReturnValue({}); firebase.onValue.mockImplementation((_ref, callback) => { firebase.callback = callback; return vi.fn(); });
  const cleanup = subscribeLiveScriptedInput({} as never, 7, "v", "boot", presentation, { getCurrentIndex: () => 0, sendScriptedInput } as never, () => ({ pageId: "page", elementId: "s", mountRevision: currentMountRevision }), createLiveScriptedInputTracker());
  return { sendScriptedInput, cleanup, setMount: (value: number) => { currentMountRevision = value; } };
}
describe("live Scripted input subscriber", () => {
  it("dispatches exact decimal values from object and array trees only once", () => { const { sendScriptedInput } = setup(); firebase.callback?.({ val: () => ({ 0: { 0: input() } }) }); firebase.callback?.({ val: () => [[input()]] }); expect(sendScriptedInput).toHaveBeenCalledExactlyOnceWith("s", "n", .12); });
  it("dispatches boolean input-output values", () => { const { sendScriptedInput } = setup(); firebase.callback?.({ val: () => ({ 0: { 1: input({ portId: "b", value: true }) } }) }); expect(sendScriptedInput).toHaveBeenCalledWith("s", "b", true); });
  it("rejects incompatible ports, values, identities, and mount", () => { const { sendScriptedInput } = setup(); const invalid = [input({ portId: "out", value: true }), input({ portId: "act", value: true }), input({ value: true }), input({ activationRevision: 8 }), input({ currentVersionId: "old" }), input({ targetBootId: "other" }), input({ pageId: "other" }), input({ elementId: "other" }), input({ targetMountRevision: 1 }), input({ value: -1 }), input({ value: 2 })]; invalid.forEach((record, index) => firebase.callback?.({ val: () => ({ 0: { [index]: record } }) })); expect(sendScriptedInput).not.toHaveBeenCalled(); });
  it("applies only higher revisions and starts a new mount epoch at one", () => { const { sendScriptedInput, setMount } = setup(); firebase.callback?.({ val: () => ({ 0: { 0: input({ revision: 2, value: .12 }) } }) }); firebase.callback?.({ val: () => ({ 0: { 0: input({ revision: 2, value: .2 }) } }) }); firebase.callback?.({ val: () => ({ 0: { 0: input({ revision: 4, value: .3 }) } }) }); setMount(3); firebase.callback?.({ val: () => ({ 0: { 0: input({ revision: 1, targetMountRevision: 3, value: .4 }) } }) }); expect(sendScriptedInput.mock.calls).toEqual([["s", "n", .12], ["s", "n", .3], ["s", "n", .4]]); });
  it("consumes an inapplicable mount record so it cannot replay", () => { const { sendScriptedInput, setMount } = setup(); firebase.callback?.({ val: () => ({ 0: { 0: input({ targetMountRevision: 3, value: .2 }) } }) }); setMount(3); firebase.callback?.({ val: () => ({ 0: { 0: input({ targetMountRevision: 3, value: .2 }) } }) }); firebase.callback?.({ val: () => ({ 0: { 0: input({ targetMountRevision: 3, revision: 2, value: .3 }) } }) }); expect(sendScriptedInput).toHaveBeenCalledExactlyOnceWith("s", "n", .3); });
});
