import type { DocsGroup, DocsTopic } from "./docs-content-types";

function elementTopic(
  id: string,
  title: string,
  what: string,
  when: string,
  inspector: string,
  layout: string,
  example: string,
  notes: string,
  controls: readonly (readonly string[])[],
): DocsTopic {
  return {
    id: `element-${id}`,
    title,
    summary: what,
    sections: [
      { title: "O que é", paragraphs: [what] },
      { title: "Quando usar", paragraphs: [when] },
      {
        title: "Inspector",
        paragraphs: [inspector],
        table: { columns: ["Seção", "Controle", "Uso"], rows: controls },
      },
      { title: "Comportamento no layout", paragraphs: [layout] },
      { title: "Exemplo básico", codeBlocks: [{ language: "text", code: example }] },
      { title: "Notas / limites", paragraphs: [notes] },
    ],
  };
}

export const elementDocsGroup: DocsGroup = {
  title: "Elementos e Inspector",
  topics: [
    elementTopic(
      "text", "Text",
      "Text apresenta uma string ou rich text em um slide.",
      "Use para títulos, parágrafos, legendas e qualquer conteúdo textual que não precise ser executado.",
      "A ordem específica é Content, Typography, Appearance, Effects e, quando o contexto permite, Position. Link aparece na seção de interação.",
      "Text participa do fluxo do Container. Seu layout textual não expõe a seção Tamanho comum; largura e quebra seguem o Container e a tipografia.",
      "variant: body\ncontent: \"Olá, PowerShow\"",
      "Typography pode estar vinculada a um estilo de texto. Desanexar cria valores locais; isso é diferente de mudar a árvore do documento.",
      [["Content", "Rich text", "Edita texto e marcas inline."], ["Typography", "Style / font fields", "Escolhe estilo, família, tamanho, peso, alinhamento e demais campos tipográficos."], ["Appearance", "Color / Background / Gradient / Pattern / Border / Rounded corners / Opacity", "Controla a superfície visual."], ["Effects", "Text stroke / Shadow", "Aplica efeitos de texto e sombra."], ["Link", "URL / Open in", "Configura link HTTP(S) do elemento."]],
    ),
    elementTopic(
      "container", "Container",
      "Container é a primitiva recursiva de composição: pode representar row, column, header, main, footer ou content e pode conter elementos mistos.",
      "Use para estruturar slides e agrupar conteúdo que deve compartilhar fluxo, espaçamento, aparência ou posicionamento.",
      "O ContainerInspector mostra Linked Style, Layout, Position, Size, Spacing, Appearance, Effects e interação. Os nomes exibidos são os das seções reutilizadas do Inspector.",
      "O layout do Container governa direção Flow/Stack, alinhamento, overflow, distribuição, encaixe de filhos, padding e margem. Position e layer controls dependem de parent/contexto.",
      "role: column\nchildren:\n  - text\n  - image\n  - table",
      "Children fit só pode ser habilitado quando o Container tem tamanho de conteúdo mensurável. Estilos vinculados podem fornecer valores efetivos sem os gravar localmente.",
      [["Linked Style", "Attach / Detach", "Usa ou remove um estilo de Container da Presentation."], ["Layout", "Direction / Overflow / Alignment / Distribution / Children fit", "Controla composição dos filhos."], ["Position", "Anchor / X offset / Y offset", "Posiciona o Container quando essa opção está disponível."], ["Size", "Preset / Width / Height", "Define dimensões ou usa preset."], ["Spacing", "Padding / Margin", "Define espaçamentos por lado ou agrupados."], ["Appearance", "Color / Background / Border / Pattern", "Define a superfície."], ["Effects", "Opacity / Shadow", "Define efeitos."], ["Interaction", "Link", "Configura destino do Container."]],
    ),
    elementTopic(
      "image", "Image",
      "Image exibe uma mídia por URL, com texto alternativo e ajuste de enquadramento.",
      "Use para uma imagem única que precisa de crop, ponto focal, proporção ou link próprios.",
      "A ordem é Source (Source, Alternative text, Fit, Crop, Focal point), Size, Appearance, Effects e Interaction. Size inclui Preserve size e preservação de proporção conforme o estado do canvas.",
      "A imagem ocupa o retângulo do layout. contain preserva a imagem inteira, cover preenche recortando e fill estica para preencher.",
      "src: https://example.com/photo.jpg\nalt: \"Diagrama\"\nfit: contain",
      "Source é uma string; o próprio elemento não faz upload. Crop e focal point são opcionais e um crop que cobre toda a fonte é omitido pelo schema.",
      [["Source", "Source", "URL da imagem."], ["Source", "Alternative text", "Texto alternativo."], ["Source", "Fit", "contain, cover ou fill."], ["Source", "Crop / Focal point", "Recorta e escolhe o ponto de atenção; controles de canvas aparecem quando ativados."], ["Size", "Width / Height / Preserve size", "Dimensiona o elemento."], ["Appearance", "Rounded corners / Opacity", "Arredonda e torna transparente."], ["Effects", "Shadow", "Aplica sombra outer/inset."], ["Interaction", "URL / Open in", "Torna a imagem um link."]],
    ),
    elementTopic(
      "gallery", "Gallery",
      "Gallery apresenta uma lista de imagens e permite selecionar itens no Inspector.",
      "Use para uma sequência de imagens que compartilha enquadramento e precisa de controle de índice em Live.",
      "A seção Content mostra Fit da galeria, lista/contador de itens, Add, Remove e, para o item selecionado, Source, Name (texto alternativo) e Fit herdado ou próprio. Depois vêm Appearance e Effects.",
      "Gallery é um elemento dimensionável e pode receber Position quando está dentro de um contexto com layer controls. Cada item pode substituir o fit da galeria.",
      "fit: contain\nitems:\n  - src: https://example.com/one.jpg\n    alt: \"Primeira imagem\"",
      "Não há uma seção de Size própria no GalleryInspector; o tamanho/posição comum é injetado pelo ElementInspector quando aplicável.",
      [["Content", "Fit", "Fit padrão dos itens."], ["Content", "Add / Remove / item selector", "Gerencia a lista e seleciona um item."], ["Content", "Source / Name / Fit", "Edita o item selecionado; Fit vazio herda o da galeria."], ["Appearance", "Background / Rounded corners / Opacity / Border", "Controla a caixa da galeria."], ["Effects", "Shadow", "Aplica sombra."]],
    ),
    elementTopic(
      "code", "Code",
      "Code exibe código com linguagem, números de linha e linhas destacadas.",
      "Use para mostrar código fonte como conteúdo de apresentação, sem executá-lo.",
      "A ordem é Content (Source, Language), Display (Show line numbers, Highlighted lines), Typography, Appearance e Effects. Position é comum quando o contexto permite.",
      "Code é um bloco dimensionável; linhas e destaque são renderizados dentro de sua caixa. Highlighted lines recebe números separados por vírgula.",
      "language: ts\nshowLineNumbers: true\nhighlightedLines: [1, 3]\ncode: |\n  const answer = 42;",
      "Language é texto e a linguagem não transforma o conteúdo em script executável. O schema usa highlightedLines como inteiros positivos.",
      [["Content", "Source", "Edita o conteúdo exibido."], ["Content", "Language", "Identifica a linguagem para a apresentação."], ["Display", "Show line numbers", "Exibe ou oculta números."], ["Display", "Highlighted lines", "Lista números de linha separados por vírgulas."], ["Typography", "Font fields", "Controla tipografia do código."], ["Appearance", "Color / Background / Border / Pattern", "Controla visual."], ["Effects", "Shadow", "Aplica sombra."]],
    ),
    elementTopic(
      "terminal", "Terminal",
      "Terminal exibe linhas semânticas de command, output, error e comment.",
      "Use para mostrar uma sessão de terminal com prompt, saída e erros diferenciados.",
      "A ordem é Content (Title e Lines), Typography, Appearance e Effects. Lines tem Add line, Remove line e um tipo por linha.",
      "Terminal é uma composição dimensionável. A cor de cada semântica é controlada pela Appearance; as linhas não executam comandos.",
      "title: \"Build\"\nlines:\n  - type: command\n    content: \"pnpm test\"\n  - type: output\n    content: \"passed\"",
      "Uma linha vazia ou sem linhas é representada pelo estado vazio do Inspector. Terminal é somente apresentação de conteúdo.",
      [["Content", "Title", "Título visual/formatado do terminal."], ["Content", "Lines / type", "Adiciona e classifica linhas command, output, error ou comment."], ["Typography", "Title / content typography", "Edita tipografia do título e das linhas."], ["Appearance", "Semantic colors / Background / Border", "Colore semânticas e superfície."], ["Effects", "Shadow", "Aplica sombra."]],
    ),
    elementTopic(
      "table", "Table",
      "Table apresenta dados em modo simple ou uma tabela estruturada com células compostas.",
      "Use simple para dados tabulares diretos e structured quando headers/células precisam de conteúdo e layout próprios.",
      "Simple tem Columns, Typography, Rows, Appearance e Effects. Structured acrescenta General (Show header), mantendo Columns, Rows, Appearance e Effects. O contador mostra a quantidade real.",
      "Table é dimensionável e pode ser posicionado por layer context. A estrutura interna define células; o tamanho externo define a caixa da tabela.",
      "mode: simple\ncolumns: [{ key: name, label: Name }]\nrows: [{ name: PowerShow }]",
      "Rows structured precisam ter exatamente uma célula por coluna. Valores simple podem ser texto, número, boolean ou null.",
      [["Columns", "Label / Key / Add / Remove", "Define colunas; Key é identidade dos dados simple."], ["Rows", "Cell editor / Add / Remove", "Edita valores ou slots estruturados."], ["General", "Show header", "Disponível no modo structured."], ["Typography", "Font fields", "Controla texto da tabela."], ["Appearance", "Color / Background / Border", "Controla dados e superfície."], ["Effects", "Shadow", "Aplica sombra."]],
    ),
    elementTopic(
      "topics", "Topics",
      "Topics apresenta uma árvore hierárquica de itens com conteúdo em cada tópico.",
      "Use para sumários, listas com subníveis ou conteúdo que precisa de hierarquia visível.",
      "A seção Content contém itens editáveis, Add topic, Add subtopic, Remove topic, List type, Topic spacing, tipografia, Text color, Markers, First-level marker e Marker color.",
      "Os tópicos são recursivos e a indentação acompanha a profundidade. Position é adicionado pelo ElementInspector quando há contexto de camadas.",
      "kind: unordered\nitems:\n  - content: \"Comece aqui\"\n    children: []",
      "A profundidade estrutural máxima atual é 5. Conteúdo não textual dentro do slot é resumido no Inspector; não é um novo tipo de tópico.",
      [["Content", "Topics / Add topic / Add subtopic / Remove topic", "Edita a árvore e seus textos."], ["Content", "List type", "Bulleted ou Numbered."], ["Content", "Topic spacing", "Espaçamento em px; pode herdar o default."], ["Content", "Text color / Typography", "Define aparência textual."], ["Markers", "First-level marker / Marker color", "Escolhe marcador permitido conforme o tipo da lista."]],
    ),
    elementTopic(
      "divider", "Divider",
      "Divider é uma linha ou separador visual horizontal ou vertical.",
      "Use para separar regiões de um slide sem adicionar conteúdo semântico.",
      "A ordem é Layout (Direction), Size (Width, Height) e Appearance (Background, Border e opções de borda disponíveis). Position pode ser adicionado pelo contexto comum.",
      "Orientation define a direção. Width e Height são entradas dimensionais; o renderer usa o retângulo resultante para desenhar o separador.",
      "orientation: horizontal\nlayout: { width: 100%, height: 2px }",
      "Não há Effects genérico neste Inspector: Divider usa seu próprio DividerEffectSchema. Width/Height são efetivos e podem depender do layout pai.",
      [["Layout", "Direction", "Horizontal ou vertical."], ["Size", "Width / Height", "Dimensões do separador."], ["Appearance", "Background", "Cor do separador."], ["Appearance", "Border / border paint", "Borda quando configurada."]],
    ),
    elementTopic(
      "embed", "Embed",
      "Embed incorpora uma URL HTTP(S) externa em uma viewport ajustável.",
      "Use para conteúdo remoto que deve aparecer dentro do slide e que aceita ser exibido em iframe.",
      "A ordem é Content (URL incorporada, Título de acessibilidade), Viewport do Embed (Zoom e Enquadramento: Superior, Direita, Inferior, Esquerda), Appearance e Effects.",
      "Embed é dimensionável e pode receber Position no contexto de camadas. Zoom e framing ajustam a página incorporada dentro da caixa.",
      "src: https://example.com\ntitle: \"Página de referência\"\nviewport: { zoom: 1 }",
      "A URL precisa ser absoluta HTTP ou HTTPS. O conteúdo não é interativo no canvas do Studio; teste na Prévia ou no Player. O site remoto também pode recusar iframe.",
      [["Content", "URL incorporada", "URL absoluta HTTP(S)."], ["Content", "Título de acessibilidade", "Título não vazio para tecnologias assistivas."], ["Viewport do Embed", "Zoom", "Valor entre 0.1 e 4."], ["Viewport do Embed", "Enquadramento", "Offsets não negativos por lado."], ["Appearance", "Background / Rounded corners / Opacity", "Controla a caixa."], ["Effects", "Shadow", "Aplica sombra."]],
    ),
    elementTopic(
      "blocks", "Blocks",
      "Blocks apresenta uma fonte de programação visual estruturada e seu diagnóstico de sintaxe.",
      "Use para demonstrações de blocos, sem executar a fonte diretamente no Inspector.",
      "A ordem é Content (Blocks source e status de sintaxe), Appearance (cores por categoria, uncategorized, text color e block stroke) e Effects.",
      "Blocks é dimensionável e seu source é convertido pelo renderer em blocos visuais. Position é comum quando o contexto de layer controls o permite.",
      String.raw`\start[events,color=#FFD500](Quando Arduino UNO iniciar)
\scope[control,color=#FFAB19](repetir \value(3)){
  \statement[output,color=#4C97FF](definir saída do pino \value(3) como \[ALTO\])
  \statement[output,color=#4C97FF](definir saída do pino \value(4) como \[BAIXO\])
  \statement[control,color=#FFAB19](esperar \value(1) segundos)
  \statement[output,color=#4C97FF](definir saída do pino \value(3) como \[BAIXO\])
  \statement[output,color=#4C97FF](definir saída do pino \value(4) como \[ALTO\])
  \statement[control,color=#FFAB19](esperar \value(1) segundos)
}`,
      "Uma fonte inválida mostra diagnóstico com linha/coluna. `\\start(...)` é o bloco inicial; `\\statement(...)` é um comando comum; `\\scope(...){ ... }` contém outros blocos; `\\value(...)` é um reporter de valor; `\\logic(...)` é um reporter lógico/booleano; `\\variable(...)` representa uma variável; `\\[…]` é uma opção visual/dropdown; e `[category,color=#...]` é uma annotation opcional de categoria e cor. Os controles de cor usam defaults por categoria e podem voltar a Use default.",
      [["Content", "Blocks source", "Edita a fonte."], ["Content", "Syntax valid / diagnostic", "Informa o resultado do parser."], ["Appearance", "Category colors / Uncategorized / Text color", "Colore blocos e texto."], ["Appearance", "Block stroke", "Controla o traço dos blocos."], ["Effects", "Shadow", "Aplica sombra."]],
    ),
    elementTopic(
      "plot", "Plot",
      "Plot representa uma ou mais equações matemáticas restritas e as renderiza como geometria 2D ou superfície 3D.",
      "Use para funções, relações implícitas e superfícies que precisam de eixos, cores ou animação. Consulte os Guias avançados para a sintaxe.",
      "Plot possui Content (Source), Animation e Appearance. Appearance contém Fit to axes, Show axes, Axis color, Axis opacity, Axis thickness, Color, Background e 3D color; a seção Size é adicionada pelo ElementInspector e Position depende do contexto.",
      "O renderer amostra a expressão em um viewport matemático e produz SVG. Fit to axes deriva uma viewport dos bounds finitos; isso não altera o source.",
      "source: y = sin(x)\nfitToAxes: true\nshowAxes: true",
      "Source tem máximo de 4096 caracteres. A linguagem é restrita: não use JavaScript, comparações ou funções que não estejam na referência matemática.",
      [["Content", "Source", "Equações com até 4096 caracteres."], ["Animation", "Animate parameter / Parameter / From / To / Duration (ms)", "Cria uma animação validada."], ["Animation", "Loop / Autoplay / Apply / Reset", "Configura e salva a animação."], ["Animation", "Play/Pause/Reset preview", "Controla apenas a prévia quando disponível."], ["Appearance", "Fit to axes / Show axes", "Ajusta viewport e eixos."], ["Appearance", "Axis color / opacity / thickness", "Estiliza eixos."], ["Appearance", "Color / Background / 3D color", "Estiliza curvas, fundo e gradiente Z."]],
    ),
    elementTopic(
      "scripted", "Scripted",
      "Scripted reúne HTML, CSS e JavaScript authored em um iframe isolado, com uma bridge explícita de Ports.",
      "Use quando a interação precisa de código authored e não é coberta por um elemento oficial. Para o fluxo completo, consulte os Guias avançados.",
      "A seção Content contém Título, HTML, CSS, JavaScript, Ports, Add port, Remove port, Label, ID, Type, Direction, Min, Max e Step, além de Aplicar / Executar e Reverter. Depois vêm Appearance e Effects.",
      "Scripted é dimensionável e pode receber Position pelo ElementInspector quando há layer context. O renderer recria o iframe quando o authored state canônico muda.",
      "title: \"Counter\"\nhtml: <button id=increment>+</button>\nscript: button.addEventListener(\"click\", increment)",
      "Digitar mantém drafts locais. Apenas Aplicar / Executar escreve o conjunto authored no documento; o Inspector nunca executa JavaScript diretamente.",
      [["Content", "Title / HTML / CSS / JavaScript", "Edita os quatro campos authored."], ["Content", "Ports", "Lista e seleciona portas."], ["Content", "Label / ID / Type / Direction", "Define a interface técnica da porta."], ["Content", "Min / Max / Step", "Restrições opcionais para portas number."], ["Content", "Aplicar / Executar", "Valida e envia o conjunto authored ao estado canônico."], ["Content", "Reverter", "Descarta drafts locais sem executar."], ["Appearance", "Background / Rounded corners / Opacity", "Controla a caixa."], ["Effects", "Shadow", "Aplica sombra."]],
    ),
    elementTopic(
      "interactive", "Interactive",
      "Interactive é um elemento canônico para widgets oficiais como function-plot, geometry-board, pwm-demo e electric-circuit.",
      "Use somente quando houver um widget oficial compatível com o contrato do elemento.",
      "Interactive não possui Inspector dedicado no Studio atual. O ElementInspector mostra Elemento e ID; quando o contexto de layers permite, a seção Position comum pode aparecer.",
      "O layout é um PositionedElementLayout. A configuração do widget é um registro canônico, mas não há no Studio atual um fluxo geral de edição dessa configuração.",
      "type: interactive\nwidget: function-plot\nconfig: {}",
      "Não invente controles de autoria para Interactive. A ausência de Inspector dedicado é o estado atual do produto; futuros widgets precisam de contrato próprio.",
      [["Common", "Element / ID", "Identifica o elemento."], ["Common, condicional", "Position", "Disponível quando o contexto de layers permite."], ["Dedicated Inspector", "Nenhum", "Não há controles específicos atuais."]],
    ),
  ],
};
