import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ ref: vi.fn(), runTransaction: vi.fn(), getDatabase: vi.fn(), getCurrentNonAnonymousUser: vi.fn(), getApps: vi.fn(() => []), initializeApp: vi.fn(() => ({})) }));
vi.mock("firebase/database", () => ({ ref: mocks.ref, runTransaction: mocks.runTransaction, getDatabase: mocks.getDatabase, set: vi.fn() }));
vi.mock("firebase/app", () => ({ getApps: mocks.getApps, initializeApp: mocks.initializeApp, getApp: vi.fn(() => ({})) }));
vi.mock("../src/features/auth/firebase-auth", () => ({ getCurrentNonAnonymousUser: mocks.getCurrentNonAnonymousUser }));
import { buildGalleryControlRootPath, buildGalleryControlSlotPath, parseLiveGalleryControlState } from "../src/features/live/gallery-control";
import { writeGalleryControlState } from "../src/features/control/control-command-writer";
const valid = (overrides: Record<string, unknown> = {}) => ({ activationRevision: 2, currentVersionId: "v", revision: 1, pageId: "p", elementId: "gallery", targetIndex: 0, expanded: false, ...overrides });
describe("gallery control wire and writer", () => {
  beforeEach(() => { vi.clearAllMocks(); vi.stubEnv("NEXT_PUBLIC_FIREBASE_API_KEY", "k"); vi.stubEnv("NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN", "d"); vi.stubEnv("NEXT_PUBLIC_FIREBASE_PROJECT_ID", "p"); vi.stubEnv("NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET", "b"); vi.stubEnv("NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID", "m"); vi.stubEnv("NEXT_PUBLIC_FIREBASE_APP_ID", "a"); vi.stubEnv("NEXT_PUBLIC_FIREBASE_DATABASE_URL", "https://x"); mocks.getDatabase.mockReturnValue({}); mocks.ref.mockImplementation((_d, path) => ({ path })); mocks.getCurrentNonAnonymousUser.mockReturnValue({ uid: "u" }); mocks.runTransaction.mockImplementation(async (_r, updater) => { const value = updater(null); return { committed: true, snapshot: { val: () => value } }; }); }); afterEach(() => vi.unstubAllEnvs());
  it("builds numeric slot paths and rejects invalid slots", () => { expect(buildGalleryControlRootPath()).toBe("live/galleryControl"); expect(buildGalleryControlSlotPath(0)).toBe("live/galleryControl/0"); expect(buildGalleryControlSlotPath(12)).toBe("live/galleryControl/12"); expect(() => buildGalleryControlSlotPath(-1)).toThrow(); expect(() => buildGalleryControlSlotPath(1.5)).toThrow(); });
  it("strictly parses and preserves exact canonical element ids", () => { expect(parseLiveGalleryControlState(valid({ elementId: " " }))).toMatchObject({ elementId: " " }); expect(parseLiveGalleryControlState(valid({ elementId: " gallery / #% " }))).toMatchObject({ elementId: " gallery / #% " }); for (const value of [{ ...valid(), extra: true }, valid({ revision: 0 }), valid({ revision: 1.5 }), valid({ targetIndex: -1 }), valid({ targetIndex: 0.5 }), valid({ expanded: "x" })]) expect(parseLiveGalleryControlState(value)).toBeNull(); });
  it("writes revision one, increments identical records, and resets exact identity changes", async () => { let previous: unknown = null; mocks.runTransaction.mockImplementation(async (_r, updater) => { const value = updater(previous); previous = value; return { committed: true, snapshot: { val: () => value } }; }); expect(await writeGalleryControlState({} as never, 2, "v", "p", 0, " ", 0, false)).toMatchObject({ revision: 1, elementId: " " }); expect(await writeGalleryControlState({} as never, 2, "v", "p", 0, " ", 1, true)).toMatchObject({ revision: 2 }); expect(await writeGalleryControlState({} as never, 2, "v", "p", 0, "gallery", 0, false)).toMatchObject({ revision: 1 }); });
  it("resets revision for every changed identity generation", async () => { for (const [activation, version, page, element] of [[2, "v", "page-b", "gallery"], [3, "v", "page-a", "gallery"], [2, "v2", "page-a", "gallery"], [2, "v", "page-a", " gallery "]] as const) { mocks.runTransaction.mockImplementationOnce(async (_r, updater) => { const value = updater(valid({ pageId: "page-a", elementId: "gallery", revision: 8 })); return { committed: true, snapshot: { val: () => value } }; }); await expect(writeGalleryControlState({} as never, activation, version, page, 0, element, 0, false)).resolves.toMatchObject({ revision: 1 }); } });
  it("requires auth and rejects malformed inputs before transaction", async () => { mocks.getCurrentNonAnonymousUser.mockReturnValue(null); await expect(writeGalleryControlState({} as never, 2, "v", "p", 0, "g", 0, false)).rejects.toThrow(); expect(mocks.runTransaction).not.toHaveBeenCalled(); mocks.getCurrentNonAnonymousUser.mockReturnValue({ uid: "u" }); await expect(writeGalleryControlState({} as never, -1, "v", "p", 0, "g", 0, false)).rejects.toThrow(); await expect(writeGalleryControlState({} as never, 2, "v", "p", 0, "", 0, false)).rejects.toThrow(); expect(mocks.runTransaction).not.toHaveBeenCalled(); });
  it("rejects all malformed runtime inputs before transacting", async () => { for (const args of [[2, "v", "p", -1, "g", 0, false], [2, "v", "p", 0.5, "g", 0, false], [2, "v", "p", 0, "g", -1, false], [2, "v", "p", 0, "g", 0.5, false], [2, "v", "p", 0, "g", 0, "yes"]] as const) await expect(writeGalleryControlState({} as never, ...args as never)).rejects.toThrow(); expect(mocks.runTransaction).not.toHaveBeenCalled(); });
  it("rejects uncommitted and malformed committed transaction results", async () => { mocks.runTransaction.mockResolvedValueOnce({ committed: false, snapshot: { val: () => valid() } }); await expect(writeGalleryControlState({} as never, 2, "v", "p", 0, "g", 0, false)).rejects.toThrow(/did not commit/); mocks.runTransaction.mockResolvedValueOnce({ committed: true, snapshot: { val: () => valid({ revision: 0 }) } }); await expect(writeGalleryControlState({} as never, 2, "v", "p", 0, "g", 0, false)).rejects.toThrow(/malformed/); });
});
