// @vitest-environment jsdom
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { PresentationSchema } from "@powershow/document-schema";
import { PresenterView } from "../src/features/control/presenter/presenter-view";
import type { ControlScriptedStateGroup } from "../src/features/control/use-live-scripted-state-control";
import { StudioI18nProvider } from "../src/features/i18n/studio-i18n-context";
vi.mock("../src/features/control/presenter/use-presenter-notes", () => ({ usePresenterNotes: () => ({ kind: "idle" }) }));
Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true });
const presentation = PresentationSchema.parse({ schemaVersion: 1, id: "p", title: "P", slides: [{ id: "page", title: "Page" }] });
const port = (overrides: Record<string, unknown> = {}) => ({ portIndex: 1, portId: "value", label: "Value", kind: "number" as const, direction: "input-output" as const, min: 0, max: 1, step: .5, runtimeKey: '["boot",2]', runtimeAvailable: true, desiredValue: null, desiredRevision: null, reportedValue: .12, reportRevision: 1, appliedInputRevision: 0, status: "ready" as const, writable: true, ...overrides });
const group = (ports = [port()]): ControlScriptedStateGroup => ({ scriptedSlot: 0, elementId: "script", title: "Script", ports });
describe("Presenter Scripted state controls", () => {
 let root: Root; let node: HTMLDivElement; let groups: ControlScriptedStateGroup[]; const setPortValue = vi.fn();
 const render = () => act(() => root.render(<StudioI18nProvider><PresenterView view={{ enabled: true, desiredPageId: "page", desiredPageIndex: 0, actualPageId: "page", actualPageIndex: 0, status: { kind: "synced" } }} sendFailed={false} presentationState={{ kind: "ready", presentation, livePresentation: presentation, displayIndex: 0, pendingVersion: null }} galleries={[]} scriptedActionGroups={[]} scriptedActionsEnabled={true} scriptedStateGroups={groups} promotingVersionId={null} failedPromotionVersionId={null} previous={vi.fn()} next={vi.fn()} goTo={vi.fn()} followPlayer={vi.fn()} updatePlayer={vi.fn()} requestFullscreen={vi.fn()} nextGallery={vi.fn()} setGalleryExpanded={vi.fn()} triggerScriptedAction={vi.fn()} setScriptedPortValue={setPortValue} end={vi.fn()} /></StudioI18nProvider>));
 beforeEach(() => { node = document.createElement("div"); document.body.append(node); root = createRoot(node); groups = [group()]; setPortValue.mockReset(); render(); }); afterEach(async () => { await act(async () => root.unmount()); document.body.innerHTML = ""; });
 it("keeps desired number blank when only actual exists, applies exact decimals, and resets drafts on mount", () => { const input = node.querySelector<HTMLInputElement>('input[type="number"]')!; expect(input.value).toBe(""); expect(node.textContent).toContain("Actual: 0.12"); act(() => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value")?.set?.call(input, "0.12"); input.dispatchEvent(new Event("input", { bubbles: true })); }); act(() => Array.from(node.querySelectorAll("button")).find((button) => button.textContent === "Apply")?.click()); expect(setPortValue).toHaveBeenCalledWith(0, 1, .12); groups = [group([port({ runtimeKey: '["boot",3]' })])]; render(); expect(node.querySelector<HTMLInputElement>('input[type="number"]')?.value).toBe(""); });
 it("renders boolean desired commands separately from actual and status", () => { groups = [group([{ ...port({ portIndex: 2, portId: "flag", label: "Flag", kind: "boolean", desiredValue: true, reportedValue: false, status: "divergent" }) }])]; render(); const buttons = Array.from(node.querySelectorAll("button")); expect(buttons.find((button) => button.textContent === "On")?.getAttribute("aria-pressed")).toBe("true"); expect(node.textContent).toContain("Actual: Off"); expect(node.textContent).toContain("Actual differs"); buttons.find((button) => button.textContent === "Off")?.click(); expect(setPortValue).toHaveBeenCalledWith(0, 2, false); });
 it("renders output values without commands and does not introduce a slider", () => { groups = [group([{ ...port({ portIndex: 2, portId: "out", label: "Out", direction: "output", desiredValue: null, reportedValue: true, writable: false, status: "ready" }) }])]; render(); expect(node.textContent).toContain("Actual: On"); expect(node.querySelector('input[type="number"], input[type="range"]')).toBeNull(); expect(node.textContent).not.toContain("Apply"); });
 it("keeps the state controls on the mobile interactive surface", () => { expect(node.querySelector('[data-mobile-gallery-controls]')?.textContent).toContain("Value"); });
});
