// @vitest-environment jsdom
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { PresentationSchema, type Presentation } from "@powershow/document-schema";
const mocks = vi.hoisted(() => ({ database: vi.fn(), write: vi.fn(), onValue: vi.fn(), ref: vi.fn(), callbacks: [] as Array<(snapshot: { val(): unknown }) => void>, unsubscribes: [] as ReturnType<typeof vi.fn>[] }));
vi.mock("firebase/database", () => ({ onValue: mocks.onValue, ref: mocks.ref }));
vi.mock("../src/features/control/realtime-db", () => ({ getRealtimeDatabaseOrNull: mocks.database }));
vi.mock("../src/features/control/control-command-writer", () => ({ writeScriptedInput: mocks.write }));
import { useLiveScriptedStateControl, type UseLiveScriptedStateControlResult } from "../src/features/control/use-live-scripted-state-control";
Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true });
const LIVE = { publicationId: "p", currentVersionId: "v", revision: 7 };
const READY = { kind: "ready" as const, presence: { activationRevision: 7, currentVersionId: "v", bootId: "boot", stage: "ready" as const, transitionedAt: 1 } };
const runtime = (overrides: Record<string, unknown> = {}) => ({ activationRevision: 7, currentVersionId: "v", mountRevision: 2, pageId: "page", elementId: "state", bootId: "boot", ...overrides });
const input = (overrides: Record<string, unknown> = {}) => ({ activationRevision: 7, currentVersionId: "v", revision: 3, pageId: "page", elementId: "state", portId: "n", targetBootId: "boot", targetMountRevision: 2, value: .12, ...overrides });
const report = (overrides: Record<string, unknown> = {}) => ({ activationRevision: 7, currentVersionId: "v", revision: 4, pageId: "page", elementId: "state", portId: "n", sourceBootId: "boot", mountRevision: 2, appliedInputRevision: 3, value: .12, ...overrides });
const presentation = (): Presentation => PresentationSchema.parse({ schemaVersion: 1, id: "p", title: "P", slides: [{ id: "page", title: "Page", elements: [{ id: "outer", type: "container", children: [{ id: "action", type: "scripted", title: "A", html: "", css: "", script: "", ports: [{ id: "go", label: "Go", kind: "action" }] }, { id: "state", type: "scripted", title: "State", html: "", css: "", script: "", ports: [{ id: "go", label: "Go", kind: "action" }, { id: "n", label: "N", kind: "number", direction: "input-output", min: 0, max: 1, step: .5 }, { id: "out", label: "Out", kind: "boolean", direction: "output" }, { id: "in", label: "In", kind: "boolean", direction: "input" }] }] }] }] });
describe("useLiveScriptedStateControl", () => {
 let root: Root; let node: HTMLDivElement; let result: UseLiveScriptedStateControlResult | null; let options: Parameters<typeof useLiveScriptedStateControl>[0];
 function Harness() { result = useLiveScriptedStateControl(options); return null; }
 async function render() { await act(async () => root.render(<Harness />)); }
 async function emit(values: [unknown, unknown, unknown]) { await act(async () => values.forEach((value, index) => mocks.callbacks[index]?.({ val: () => value }))); }
 beforeEach(async () => { node = document.createElement("div"); document.body.append(node); root = createRoot(node); result = null; options = { live: LIVE, livePresentation: presentation(), desiredPageId: "page", actualPageId: "page", controlSynced: true, playerStatus: READY, controlsBlocked: false }; mocks.database.mockReturnValue({ db: true }); mocks.ref.mockImplementation((_db, path) => ({ path })); mocks.onValue.mockImplementation((_ref, callback) => { mocks.callbacks.push(callback); const unsubscribe = vi.fn(); mocks.unsubscribes.push(unsubscribe); return unsubscribe; }); mocks.write.mockResolvedValue({}); await render(); });
 afterEach(async () => { await act(async () => root.unmount()); document.body.innerHTML = ""; mocks.callbacks.length = 0; mocks.unsubscribes.length = 0; vi.clearAllMocks(); });
 it("discovers nested stateful ports using every Scripted slot and real port indexes", () => { expect(result?.groups.map((group) => ({ slot: group.scriptedSlot, id: group.elementId, ports: group.ports.map((port) => [port.portIndex, port.portId, port.direction]) }))).toEqual([{ slot: 1, id: "state", ports: [[1, "n", "input-output"], [2, "out", "output"], [3, "in", "input"]] }]); });
 it("hydrates exact current runtime/input/report and derives ready, pending, divergent, and awaiting report", async () => { await emit([{ 1: runtime() }, { 1: { 1: input() } }, { 1: { 1: report() } }]); expect(result?.groups[0]?.ports[0]).toMatchObject({ desiredValue: .12, desiredRevision: 3, reportedValue: .12, appliedInputRevision: 3, status: "ready", writable: true }); await emit([{ 1: runtime() }, { 1: { 1: input() } }, { 1: { 1: report({ appliedInputRevision: 2 }) } }]); expect(result?.groups[0]?.ports[0]?.status).toBe("pending"); await emit([{ 1: runtime() }, { 1: { 1: input() } }, { 1: { 1: report({ value: .2 }) } }]); expect(result?.groups[0]?.ports[0]?.status).toBe("divergent"); expect(result?.groups[0]?.ports[1]?.status).toBe("awaiting-report"); expect(result?.groups[0]?.ports[2]).toMatchObject({ desiredValue: null, status: "ready" }); });
 it("accepts current output and input-output initial reports without inventing desired state", async () => { await emit([{ 1: runtime() }, {}, { 1: { 1: report(), 2: report({ portId: "out", value: true, appliedInputRevision: 0 }) } }]); expect(result?.groups[0]?.ports[0]).toMatchObject({ desiredValue: null, reportedValue: .12, status: "ready" }); expect(result?.groups[0]?.ports[1]).toMatchObject({ reportedValue: true, status: "ready" }); });
 it("rejects stale runtime identity and stale mount values", async () => { await emit([{ 1: runtime({ mountRevision: 3 }) }, { 1: { 1: input() } }, { 1: { 1: report() } }]); expect(result?.groups[0]?.ports[0]).toMatchObject({ runtimeAvailable: true, desiredValue: null, reportedValue: null, status: "awaiting-report" }); await emit([{ 1: runtime({ currentVersionId: "old" }) }, {}, {}]); expect(result?.groups[0]?.ports[0]?.status).toBe("unavailable"); await emit([{ 1: runtime({ bootId: "wrong" }) }, {}, {}]); expect(result?.groups[0]?.ports[0]?.status).toBe("unavailable"); });
 it("changes the presentation-only runtime key on remount", async () => { await emit([{ 1: runtime({ mountRevision: 2 }) }, {}, {}]); expect(result?.groups[0]?.ports[0]?.runtimeKey).toBe(JSON.stringify(["boot", 2])); await emit([{ 1: runtime({ mountRevision: 3 }) }, {}, {}]); expect(result?.groups[0]?.ports[0]?.runtimeKey).toBe(JSON.stringify(["boot", 3])); });
 it("writes an exact current runtime tuple without quantizing decimals and refuses unsafe/output/no-runtime writes", async () => { await emit([{ 1: runtime() }, {}, {}]); await act(async () => { result?.setPortValue(1, 1, .12); await Promise.resolve(); }); expect(mocks.write).toHaveBeenCalledWith({ db: true }, expect.objectContaining({ scriptedSlot: 1, portIndex: 1, elementId: "state", portId: "n", targetBootId: "boot", targetMountRevision: 2, value: .12 })); await act(async () => { result?.setPortValue(1, 2, true); result?.setPortValue(1, 1, 2); }); expect(mocks.write).toHaveBeenCalledOnce(); await emit([{}, {}, {}]); await act(async () => result?.setPortValue(1, 1, .12)); options = { ...options, actualPageId: "other" }; await render(); await act(async () => result?.setPortValue(1, 1, .12)); expect(mocks.write).toHaveBeenCalledOnce(); });
 it("hides an already surfaced failure when the same Scripted remounts", async () => { mocks.write.mockRejectedValueOnce(new Error("offline")); await emit([{ 1: runtime() }, {}, {}]); await act(async () => { result?.setPortValue(1, 1, .12); await Promise.resolve(); }); expect(result?.sendFailed).toBe(true); await emit([{ 1: runtime({ mountRevision: 3 }) }, {}, {}]); expect(result?.sendFailed).toBe(false); });
 it("cleans root subscriptions and suppresses a late write failure after remount", async () => { let reject!: (reason?: unknown) => void; mocks.write.mockImplementationOnce(() => new Promise((_, fail) => { reject = fail; })); await emit([{ 1: runtime() }, {}, {}]); await act(async () => result?.setPortValue(1, 1, .12)); await emit([{ 1: runtime({ mountRevision: 3 }) }, {}, {}]); await act(async () => { reject(new Error("offline")); await Promise.resolve(); }); expect(result?.sendFailed).toBe(false); await act(async () => root.unmount()); expect(mocks.unsubscribes).toHaveLength(3); expect(mocks.unsubscribes.every((unsubscribe) => unsubscribe.mock.calls.length === 1)).toBe(true); });
});
